# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget1(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.vhod = QtWidgets.QPushButton(Widget)
        self.vhod.setGeometry(QtCore.QRect(310, 360, 161, 29))
        self.vhod.setObjectName("vhod")
        self.reg = QtWidgets.QPushButton(Widget)
        self.reg.setGeometry(QtCore.QRect(310, 400, 161, 29))
        self.reg.setObjectName("reg")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(320, 280, 141, 20))
        self.label_2.setObjectName("label_2")
        self.login = QtWidgets.QLineEdit(Widget)
        self.login.setGeometry(QtCore.QRect(310, 240, 161, 28))
        self.login.setObjectName("login")
        self.parol = QtWidgets.QLineEdit(Widget)
        self.parol.setGeometry(QtCore.QRect(310, 310, 161, 28))
        self.parol.setObjectName("parol")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(320, 210, 121, 20))
        self.label.setObjectName("label")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.vhod.setText(_translate("Widget", "Войти"))
        self.reg.setText(_translate("Widget", "Зарегистрироваться"))
        self.label_2.setText(_translate("Widget", "Введите пароль"))
        self.label.setText(_translate("Widget", "Введите логин"))
