# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget2(object):
    def setupUi(self, Widget2):
        Widget2.setObjectName("Widget2")
        Widget2.resize(901, 603)
        self.tableWidget = QtWidgets.QTableWidget(Widget2)
        self.tableWidget.setGeometry(QtCore.QRect(260, 200, 621, 281))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.add = QtWidgets.QPushButton(Widget2)
        self.add.setGeometry(QtCore.QRect(260, 150, 90, 29))
        self.add.setObjectName("add")
        self.izm = QtWidgets.QPushButton(Widget2)
        self.izm.setGeometry(QtCore.QRect(370, 150, 90, 29))
        self.izm.setObjectName("izm")
        self.spisat = QtWidgets.QPushButton(Widget2)
        self.spisat.setGeometry(QtCore.QRect(480, 150, 90, 29))
        self.spisat.setObjectName("spisat")
        self.exit = QtWidgets.QPushButton(Widget2)
        self.exit.setGeometry(QtCore.QRect(780, 490, 90, 29))
        self.exit.setStyleSheet("background-color: rgb(255, 56, 99);")
        self.exit.setObjectName("exit")
        self.toolBox = QtWidgets.QToolBox(Widget2)
        self.toolBox.setGeometry(QtCore.QRect(30, 150, 221, 161))
        self.toolBox.setObjectName("toolBox")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 221, 91))
        self.widget.setObjectName("widget")
        self.tabspis = QtWidgets.QPushButton(self.widget)
        self.tabspis.setGeometry(QtCore.QRect(0, 0, 111, 29))
        self.tabspis.setObjectName("tabspis")
        self.tabmesta = QtWidgets.QPushButton(self.widget)
        self.tabmesta.setGeometry(QtCore.QRect(0, 30, 111, 29))
        self.tabmesta.setObjectName("tabmesta")
        self.tabob = QtWidgets.QPushButton(self.widget)
        self.tabob.setGeometry(QtCore.QRect(0, 60, 111, 29))
        self.tabob.setObjectName("tabob")
        self.toolBox.addItem(self.widget, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 221, 91))
        self.page_4.setObjectName("page_4")
        self.zap2 = QtWidgets.QPushButton(self.page_4)
        self.zap2.setGeometry(QtCore.QRect(0, 0, 191, 29))
        self.zap2.setObjectName("zap2")
        self.zap3 = QtWidgets.QPushButton(self.page_4)
        self.zap3.setGeometry(QtCore.QRect(0, 30, 191, 29))
        self.zap3.setObjectName("zap3")
        self.toolBox.addItem(self.page_4, "")

        self.retranslateUi(Widget2)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Widget2)

    def retranslateUi(self, Widget2):
        _translate = QtCore.QCoreApplication.translate
        Widget2.setWindowTitle(_translate("Widget2", "Widget2"))
        self.add.setText(_translate("Widget2", "Добавить"))
        self.izm.setText(_translate("Widget2", "Изменить"))
        self.spisat.setText(_translate("Widget2", "Списать"))
        self.exit.setText(_translate("Widget2", "Выход"))
        self.tabspis.setText(_translate("Widget2", "Списанное"))
        self.tabmesta.setText(_translate("Widget2", "Рабочие места"))
        self.tabob.setText(_translate("Widget2", "Оборудование"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.widget), _translate("Widget2", "Таблицы"))
        self.zap2.setText(_translate("Widget2", "Сотрудники >3 устройств"))
        self.zap3.setText(_translate("Widget2", "Незакрепленное"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("Widget2", "Запросы"))